# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      # specify the version you desire here
      - image: rtcamp/ci-deployer
    steps:
      - checkout # check out the code in the project directory
      - save_cache: # Caches dependencies with a cache key
            # template for an environment variable,
            # see circleci.com/docs/2.0/caching/
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                  - ~/circleci-demo-workflows
      - run:
          name: PHPCS
          command: |
            echo Running phpcs script
            source ./.circleci/setup-phpcs.sh
            lint_php_files
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: SSH Key setup
          command: echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - run:
          name: Deploy
          command: |
            export PATH="$PATH:$COMPOSER_HOME/vendor/bin"
            composer require vlucas/phpdotenv --dev
            export PROJECT_ROOT="$(pwd)"
            source ./.circleci/install_test_wp.sh
            mv ./.circleci/deploy.php deploy.php
            if [ -z "$IS_VIP" -a "$IS_VIP"=="yes" ]; then source ./.circleci/install_mu_plugins.sh; fi
            export build_root
            dep deploy $CIRCLE_BRANCH

