# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

orbs:
  rtcamp: kirtangajjar/default-config@dev:0.0.1

workflows:
    version: 2
    build_and_deploy:
       jobs:
       - rtcamp/build:
          filters:
             branches:
               only:
               - develop
               - master
       - rtcamp/deploy:
          context: org-global
          server: dev5
          filters:
            branches:
              only:
              - develop
              - master
